### PR TITLE
Fixed #627: Node.js packages are outdated

### LINKED ISSUE #627: Node.js packages are outdated
### Expected Behaviour

We use `gulp` to generate static assets (images, CS, JS, etc.), and we should make sure that the Node.js dependencies are up-to-date. This is not directly related to the functionality or security of sous-chef, but fixing it would eliminate potential maintenance problems in the future.

### Actual Behaviour

Using `docker-compose`, sous-chef is automatically built with outdated Node.js, npm, and even a deprecated package. It caused a deployment error recently due to a malfunction of an old npm version. (The error is related to gifsicle ENOENT, but for this moment we have a temporary solution for it.)

1. Outdated Node.js and npm
    On Ubuntu, `apt-get install nodejs` is not getting the newest version of nodejs and npm:
````
root@525e47d51809:/code# nodejs --version                                                                                                  
v4.7.2
root@525e47d51809:/code# npm --version
2.15.11
````
(The latest versions are node.js==6.9.4LTS and npm==4.1.1)

*Note: to install the newest nodejs and npm see [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions). To install only the newest npm, it's also possible:*
````
root@525e47d51809:/code# npm --version
2.15.11
root@525e47d51809:/code# npm -g install npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
npm@4.1.1 /usr/lib/node_modules/npm
root@525e47d51809:/code# npm --version
4.1.1
````

2. Deprecated package:
````
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN optional dep failed, continuing fsevents@1.0.17
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.17
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
````
    `gulp-minify-css` has been deprecated and replaced. It introduces a few deprecated packages also.

3. Outdated packages:
    Tested with `npm -g install npm-check-updates`:
````
root@525e47d51809:/code/tools/gulp# npm-check-updates 
[INFO]: You can also use ncu as an alias
Using /code/tools/gulp/package.json
[..................] - :
 es6-promise      ^3.0.2  →  ^4.0.5 
 gulp-debug       ^2.1.2  →  ^3.0.0 
 gulp-imagemin    ^2.4.0  →  ^3.1.1 
 gulp-jsvalidate  ^2.1.0  →  ^3.0.0 
 gulp-sass        ^2.1.0  →  ^3.1.0 
 gulp-uglify      ^1.4.2  →  ^2.0.0 
````

### Steps to reproduce

N/A

### PR DESCRIPTION
**Pull request by peakwinter**
### Changes proposed in this pull request:

* Update the versions of all JS dependencies (both frontend and for Gulp)
* Import vendor JS/CSS/images from npm packages, rather than having them hard-coded into this repository.
* Set the Docker environment to use Node.JS 6.x (LTS) versions, instead of 4.x.

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

* Rebuild the Docker dev environment using `docker-compose build && docker-compose up`.
* Launch the Docker dev environment using `docker exec -it $IDOFWEBCONTAINER bash`.
* Run `node --version && npm --version`
* Ensure the new npm dependencies install properly with `cd /code/tools/gulp && npm install`
* Ensure the Gulp pipeline runs successfully with `cd /code/tools/gulp && gulp watch`
* Open the dev server at `http://localhost:8000` and ensure all assets are properly loading on various screens.

### Deployment notes and migration

- [ ] Migration is needed for this change
- [X] Environment rebuild is needed for this change

It is imperative to **rebuild your docker-compose environment** using `docker-compose build` so the new repos for Node.JS 6.x can be properly installed.

### New translatable strings

- [ ] If applicable, I have included updated .po files with new strings (see https://github.com/savoirfairelinux/sous-chef/blob/dev/docs/internationalization.adoc)

### Additional notes

none

### CODE REVIEW

File: src/frontend/js/custom-leaflet.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ function main_map_init (map, options) {
     // Create bike router using mapbox
     var bikerouter = L.Routing.mapbox('pk.eyJ1IjoicmphY3F1ZW1pbiIsImEiOiJjaXAxaWpxdGkwMm5ydGhtNG84eGdjbGthIn0.TdwCw6vhAJdgxzH0JBp6iA');
     var defaultVehicle = $('#route_map').data('selected-vehicle');
-    bikerouter.options.profile = 'mapbox.' + defaultVehicle;
+    bikerouter.options.profile = 'mapbox/' + defaultVehicle;
```
Comment (lingxiaoyang) [inline src/frontend/js/custom-leaflet.js]: Is this an API change?

Comment (peakwinter) [inline src/frontend/js/custom-leaflet.js]: Yes. Routing profiles in the Mapbox Directions API v4 have a period in them, whereas in v5 they have a slash.

File: tools/gulp/gulpfile.js [hunk 2]
```diff
@@ -1,154 +1,206 @@
...
-var sass = require('gulp-sass');
-var autoprefixer = require('gulp-autoprefixer');
-var concat = require('gulp-concat');
-var uglify = require('gulp-uglify');
-var imagemin = require('gulp-imagemin');
-var cache = require('gulp-cache');
-var debug = require('gulp-debug');
-var validate = require('gulp-jsvalidate');
+const gulp = require('gulp');
+const bytediff = require('gulp-bytediff');
```
Comment (lingxiaoyang) [inline tools/gulp/gulpfile.js]: Do we have a specific reason to change browser-sync to gulp-bytediff?

Comment (peakwinter) [inline tools/gulp/gulpfile.js]: It's not a change, rather browsersync is being removed because the dev environment doesn't support it anyway, and bytediff was added to do something different (print minification statistics).

File: tools/gulp/package.json [hunk 3]
```diff
@@ -2,20 +2,29 @@
   "name": "sous-chef-skel",
   "version": "0.0.1",
```
Comment (lingxiaoyang) [inline tools/gulp/package.json]: I do think we can bump the version :)

File: src/frontend/js/custom-leaflet.js (hunk 1 above)
Comment (lingxiaoyang) [inline src/frontend/js/custom-leaflet.js]: In line 142, there's another "mapbox." that should be changed. Can you add this?
